from Class_Punto import*
from Class_Rectangulo import*

A= Punto()
B = Punto()
C= Punto()
D = Punto()
A.set_x(2)
A.set_y(3)
B.set_x(5)
B.set_y(5)
C.set_x(-3)
C.set_y(-1)
D.set_x()
D.set_y()
xa = A.get_x()
ya = A.get_y()
xb = B.get_x()
yb = B.get_y()
xc = C.get_x()
yc = C.get_y()
xd = D.get_x()
yd = D.get_y()
puntoA = A.show()
puntoB=B.show()
puntoC=C.show()
puntoD = D.show()
print ("El punto A tiene coordenadas:", puntoA)
print("El punto B tiene coordenadas:", puntoB)
print("El punto C tiene coordenadas:", puntoC)
print("El punto D tiene coordenadas:", puntoD)
AB =A.vector(xb,yb)
BA = B.vector(xa,ya)
distancia_AB =A.distancia(xb,yb)
distancia_BA = B.distancia(xa,ya)
print ("El vector AB=", AB)
print(BA)

print(distancia_AB)
print(distancia_BA)

rectangulo = rectangulo()
rectangulo.set_punto1 (puntoA)
rectangulo.set_punto2(puntoB)

primer_punto = rectangulo.get_punto1()
segundo_punto = rectangulo.get_punto2()

print(primer_punto)
print(segundo_punto)